bidding/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^$', include('realtime_bidding.urls', namespace='realtime_bidding')),
    url(r'^branch/', include('realtime_bidding.urls', namespace='realtime_bidding')),
]

chat/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    url(r'^login/$', views.Login, name='login_new_chatroom'),
    url(r'^login/(?P<room_number>\d+)/$', views.Login, name='login'),
    url(r'^logout/$', views.Logout, name='logout'),

    url(r'^home/(?P<pk>\d+)/$', views.Home.as_view(), name='home'),
    #url(r'^new_chat_room/$', views.NewChatRoom.as_view(), name='new_chat_room'),
    #url(r'^new_chat_room/$', RedirectView.as_view(url='/chat/home'), name='new_chat_room'),
    #url(r'^new_chat_room/$', views.NewChatRoom, name='new_chat_room'),

    url(r'^bidding_post/(?P<room_number>\d+)/$', views.Bidding_Post, name='bidding_post'),
    url(r'^post/(?P<room_number>\d+)/$', views.Post, name='post'),
    url(r'^messages/(?P<pk>\d+)/$', views.Messages.as_view(), name='messages'),
    url(r'^bidding_messages/(?P<pk>\d+)/$', views.Bidding_Messages.as_view(), name='messages'),
    url(r'^forms/$', views.new_chatroom_product, name='new_chatroom_product'),
]

realtime_bidding/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
                url(r'^$', views.main.as_view(),name='index'),
                url(r'^register/$', views.register, name='register'),
                url(r'^register_page/$', views.register_page, name='register_page'),
                url(r'^my_page/$', views.my_page.as_view(), name='my_page'),
                url(r'^bidding_info/(?P<pk>\d+)/$', views.bidding_info.as_view(), name='bidding_info'),
                url(r'^confirm/(?P<pk>\d+)/$', views.confirm, name='confirm'),
                #url(r'^$', views.main)
    ]

realtime_bidding/models.py
from __future__ import unicode_literals
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import User as auth_User
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)
# Create your models here.

class User(models.Model):
    naver_id=models.CharField(max_length=20,primary_key=True)
    email=models.EmailField()
    #phone_num = models.PositiveIntegerField()

    def __unicode__(self):
        return self.naver_id

class MyUserManager(BaseUserManager):
    def create_user(self, naver_id, phone_num, address,name, email, password=None):

        if not naver_id:
            raise ValueError('Users must have an naver account')

        user = self.model(
            naver_id=naver_id,
            address=address,
            phone_num=phone_num,
            name=name,
            email=email,
        )

        user.is_admin = False
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, naver_id, phone_num, address, name, email, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.model(
            naver_id=naver_id,
            address=address,
            phone_num=phone_num,
            password=password,
            name=name,
            email=email
        )

        user.is_admin = True
        user.save(using=self._db)

        return user

class test_user(AbstractBaseUser):
    naver_id= models.CharField(max_length=20,null=True,blank=True)
    name=models.CharField(max_length=10,default="")
    email = models.EmailField(max_length=254,default="",unique=True)
    phone_num = models.CharField(max_length=11)
    address = models.CharField(max_length=254)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone_num', 'address','name']

    def __str__(self):  # __unicode__ on Python 2
        return self.email

    def get_full_name(self):
        # The user is identified by their email address
        return self.name

    def get_short_name(self):
        # The user is identified by their email address
        return self.name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Product(models.Model):
    product_id=models.AutoField(primary_key=True)
    chatting_room_id=models.ManyToManyField('Chatting_room')
    product_name=models.CharField(max_length=50)
    start_price=models.PositiveIntegerField(default=0)
    bidding_price=models.PositiveIntegerField(null=True,blank=True)
    seller_id=models.ManyToManyField(test_user,related_name='seller_id')
    buyer_id=models.EmailField(max_length=254,default="")
    information=models.CharField(max_length=200,blank=True)
    pro_image = models.ImageField(upload_to = "realtime_bidding/static/img/",null=True, blank=True)
    bidding_state=models.PositiveIntegerField(default=1) # 1 is ing, 2 is waiting for deposit 3 is done. later maybe add more state

    def __unicode__(self):
        return self.product_name

class Chatting_room(models.Model):
    room_id=models.AutoField(primary_key=True)
    chatting_history_file_path=models.CharField(max_length=300)
    bidding_history_file_path=models.CharField(max_length=300)
    room_created=models.DateTimeField(auto_now_add=True)
    rest_of_bidding = models.DateTimeField(default=timezone.localtime(timezone.now()))
    chat_done = models.BooleanField(default=False)
    bid_start = models.BooleanField(default=False)
    #chatting_history_file_path=models.FilePathField(path=settings.FILE_PATH_FIELD_DIRECTORY)
    #bidding_history_file_path=models.FilePathField(path=settings.FILE_PATH_FIELD_DIRECTORY)

    def __unicode__(self):
        return '%s' % (self.room_id)

class Chat(models.Model):
    chat_room = models.ForeignKey(Chatting_room, on_delete=models.CASCADE, default=9999)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(test_user)
    message = models.CharField(max_length=200)

    def __unicode__(self):
        return self.message

class bidding_Chat(models.Model):
    chat_room = models.ForeignKey(Chatting_room, on_delete=models.CASCADE, default=9999)
    created = models.DateTimeField(blank=True)
    user = models.ForeignKey(test_user)
    message = models.CharField(max_length=200)

    def __unicode__(self):
        return self.message

realtime_bidding/forms.py
from django import forms

class register_form(forms.Form):

    naver_id = forms.CharField(max_length=20)
    name = forms.CharField(max_length=10)
    password = forms.CharField(widget=forms.PasswordInput)
    password_check = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(max_length=254)
    phone_num = forms.CharField(max_length=11)
    address = forms.CharField(max_length=254)

class naver_register_form(forms.Form):

    phone_num = forms.CharField(max_length=11)
    address = forms.CharField(max_length=254)

realtime_bidding/views.py
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import render
from django.template import loader, Context
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from django.contrib.auth import authenticate, logout, login

from realtime_bidding.forms import register_form
from .models import Chatting_room , Product , test_user , MyUserManager


# Create your views here.

class main(ListView):

    template_name = 'index.html'
    page_num = 0
    queryset = Chatting_room.objects.all().filter(chat_done = False).order_by('room_id')
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(main, self).get_context_data(**kwargs)

        if self.request.user.is_authenticated() :
            user_email = self.request.user.email
            try:
                context['test_user'] = test_user.objects.get(email=user_email)
            except test_user.DoesNotExist:
                context['is_naver_account'] = "not"
        else:
            pass
        return context


def register_page(request):
    return render(request,'register_page.html')

def register(request):
    if request.method == 'POST':
        form = register_form(request.POST)
        if form.is_valid():

            naver_id = form.cleaned_data.get('naver_id')
            phone_num = form.cleaned_data.get('phone_num')
            name = form.cleaned_data.get('name')
            address = form.cleaned_data.get('address')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            password_check = form.cleaned_data.get('password_check')

            try:
                id_check = test_user.objects.get(email=email)
            except test_user.DoesNotExist:
                if password != password_check:
                    return HttpResponse("wrong password check! please more check")

                user = test_user.objects.create_user(naver_id, phone_num, address, name, email, password)
                user.save()
                return render(request, 'register_success.html')

            return HttpResponse("you already register in our site! please check!")

    else:
        form = register_form()
        token = request.GET.get('token','token sending error! please try again')
    return render(request, 'register.html', {'form': form })

class my_page(TemplateView):

    template_name = 'my_page.html'

    def get_context_data(self, **kwargs):
        context = super(my_page, self).get_context_data(**kwargs)

        if not self.request.user.is_authenticated():
            return HttpResponse('You must log in !')

        login_user = test_user.objects.get(email=self.request.user.email)
        context['sell_product'] = Product.objects.all().filter(seller_id=login_user).order_by('bidding_state')

        try:
            context['buy_product'] = Product.objects.all().filter(buyer_id=login_user).order_by('bidding_state')
        except :
            pass

        return context

class bidding_info(DetailView) :

    template_name = "bidding_info.html"

    model = Product

    def get_context_data(self, **kwargs):

        context = super(bidding_info, self).get_context_data(**kwargs)

        context['seller'] = Product.objects.get(product_id=self.kwargs['pk']).seller_id.all()
        context['buyer'] = Product.objects.get(product_id=self.kwargs['pk']).buyer_id
        context['test'] = Product.objects.get(product_id=self.kwargs['pk']).seller_id

        return context

def confirm(request, pk):
    product = Product.objects.get(product_id=pk)
    product.bidding_state="3"
    product.save()

    #print(product.chatting_room_id.all()[0])

    return HttpResponseRedirect('../../my_page')

realtime_bidding/templates/bidding_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="../../../static/css/realtime_bidding.css" rel="stylesheet">
    <link href="../../../static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include "header.html" %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">물품 상세 정보
            <small>{{ object.product_name }}</small>
        </h1>
    </div>
</div><br><br>

<div class="container">
    <div style = "width:45%;float:left;"><img class="img-responsive" src="{{ object.pro_image|cut:'realtime_bidding' }}" alt="" style="width:400px;height:210px;"></div>
    <div style = "width: 45%;float:left;"><table class="table table-condensed">
        <tr>
            <td>물품 이름</td>
            <td>{{ object.product_name }}</td>
        </tr>
        <tr>
            <td>최종 낙찰 가격</td>
            <td>{{ object.bidding_price }}</td>
        </tr>
        <tr>
            <td>판매자</td>
            <td>{% for a in object.seller_id.all %}{{ a.name }}{% endfor %}</td>
        </tr>
        <tr>
            <td>구매자</td><td>{% for a in object.buyer_id.all %}{{ a.name }}{% endfor %}</td>
        </tr>
        <tr>
            <td>물품 정보</td><td>{{ object.information }}</td>
        </tr>
        <tr>
            <td colspan="2" align="center"><input class="btn btn-default" type="button" value="거래완료하기" onclick="showConfirm();" /></td>
        </tr>
    </table></div>

</div>

<script>
    function showConfirm() {
 if (confirm("금액을 맞게 받으셨습니까? 확인 버튼을 누르신 이후에는 거래가 완전히 완료 됩니다."))
  {
      location.href='http://127.0.0.1:8000/branch/confirm/{{ object.product_id }}';
  } else {
   alert("취소 되었습니다.");
  }
 }

</script>
</body>
</html>

realtime_bidding/templates/header.html
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="http://127.0.0.1:8000/">Realtime-Bidding </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                        {% if not user.is_authenticated %}
                            <li>
                                <a href="http://127.0.0.1:8000/chat/login">
                                    Log in
                                </a>
                            </li>
                            <li>
                                <a href="http://127.0.0.1:8000/branch/register_page ">Register</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="http://127.0.0.1:8000/branch/my_page">My page</a>
                            </li>
                            <li>
                                <a href="http://127.0.0.1:8000/chat/logout">Log out</a>
                            </li>
                        {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

realtime_bidding/templates/index.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>3 Col Portfolio - Start Bootstrap Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/css/realtime_bidding.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../static/css/3-col-portfolio.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
{% include "header.html" %}
    <!-- Page Content -->
    <div class="container">

        <!-- Page Header -->
            <div class="col-md-6" style="height: 150px;;">
                <h1 class="page-header">    Bidding-Service
                    <small>DEMO version</small>
                </h1>
            </div>
        <div class="col-md-6" style="height:150px;">
            <div id="naver_id_register" align="right">
                <br><br><br>
                {% if user.is_authenticated %}
                    반갑습니다! {{ test_user.name }} 회원님.<br>
                    {{ test_user.email }}<br>
                {% else %}
                    <p>Welcome, Guest <br>서비스를 이용하려면 로그인 하세요!</p>
                {% endif %}
            </div>
        </div>

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-4 portfolio-item">
                <a href="/chat/forms/">
                    <img class="img-responsive" src="http://placehold.it/700x400" alt="">
                </a>
                <h3>
                    <a href="#">New Deal</a>
                </h3>
                <p>If you want to start deal, click this.</p>
            </div>
            {% for i in object_list %}
            <div class="col-md-4 portfolio-item" style="overflow-y:hidden; word-break:break-all; height: 370px;">
                {% for j in i.product_set.all %}
                <a href="/chat/home/{{ i.room_id }}">
                    {% load static %}
                    <img class="img-responsive" src="{{ j.pro_image|cut:'realtime_bidding' }}" alt="" style="width:400px;height:210px;">
                </a>
                    <h3>
                        <a href="#">{{ j.product_name }}</a>
                    </h3>
                    {% for z in j.seller_id.all %}
                        Seller ID : {{ z }}<br>
                    {% endfor %}
                    Start price : {{ j.start_price }}<br>
                    Bidding price : {{ j.bidding_price }}<br>
                    Information : {{ j.information }}<br>
                {% endfor%}
            {# <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p> #}
            </div>
            {% endfor %}
        </div>

        <hr>

        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        {% if page_obj.has_previous %}
                            <a href="/?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        {% else %}
                            <a href="#">&laquo;</a>
                        {% endif %}
                        {# <a href="#">&laquo;</a> #}
                    </li>
                    {% for page in page_obj.paginator.page_range %}
                        {% if page_obj.number == page %}
                            <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?page={{ page }}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    <li>
                        {% if page_obj.has_next %}
                            <a href="/?page={{ page_obj.next_page_number }}">&raquo;</a>
                        {% else %}
                            <a href="#">&raquo;</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>

    <!-- /.container -->

    <!-- jQuery -->
    <script src="../static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../static/js/bootstrap.min.js"></script>

    <!-- jquery cokie and naverlogin js for naver id login function-->

    <script type="text/javascript" charset="utf-8" src="../static/js/jquery_cookie/jquery.cookie.js"></script>
    <script type="text/javascript" charset="utf-8" src="../static/naver_login/naverLogin_latest.js"></script>

</body>
</html>

realtime_bidding/templates/my_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Title</title>
    <!-- Bootstrap Core CSS -->
    <link href="../../static/css/realtime_bidding.css" rel="stylesheet">
    <link href="../../static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->

    <link href="../../static/css/my_page.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body >
{% include "header.html" %}

<div class="container_mypage">
    <div id="page_left">
        <h1 align="center"> 내가 등록한 경매품</h1><br>
        <table class="table table-hover">
            <colgroup>
                <col style="width:25%;">
                <col style="width:45%">
                <col style="width:15%">
                <col style="width:15%">
            </colgroup>
            <tr>
                <th>이미지</th>
                <th>상품 정보</th>
                <th>낙찰 가격</th>
                <th>상태</th>
            </tr>
            {% for sell_pro in sell_product %}
            <tr>
                <td style="word-break: break-all;">
                    <a href="http://127.0.0.1:8000/branch/bidding_info/{{ sell_pro.product_id }}"><img class="img-responsive" src="{{ sell_pro.pro_image|cut:'realtime_bidding' }}" alt="" style="width:100%;"></a>
                </td>
                <td style="word-break: break-all;">
                    {{ sell_pro.information }}
                </td>
                <td style="word-break: break-all;">
                    {{ sell_pro.bidding_price }} 원
                </td>
                <td style="word-break: break-all;">
                    {% if sell_pro.bidding_state == 1 %}
                        경매 진행중
                    {% elif sell_pro.bidding_state == 2 %}
                        입금 확인중
                    {% elif sell_pro.bidding_state == 3 %}
                        거래 완료
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div id="page_right">
        <h1 align="center"> 내가 최종 입찰한 경매품</h1><br>
        <table class="table table-hover">
            <colgroup>
                <col style="width:25%;">
                <col style="width:45%">
                <col style="width:15%">
                <col style="width:15%">
            </colgroup>
            <tr>
                <th>이미지</th>
                <th>상품 정보</th>
                <th>낙찰 가격</th>
                <th>상태</th>
            </tr>
            {% for buy_pro in buy_product %}
            <tr >
                <td style="word-break: break-all;">
                    <a href="http://127.0.0.1:8000/branch/bidding_info/{{ buy_pro.product_id }}"><img class="img-responsive" src="{{ buy_pro.pro_image|cut:'realtime_bidding' }}" alt="" style="width:100%;"></a>
                </td>
                <td style="word-break: break-all;">
                    상품명 : {{ buy_pro.product_name  }} <br>
                    {{ buy_pro.information }}
                </td>
                <td style="word-break: break-all;">
                    {{ buy_pro.bidding_price }} 원
                </td>
                <td style="word-break: break-all;">
                    {% if buy_pro.bidding_state == 1 %}
                        거래진행중
                    {% elif buy_pro.bidding_state == 2 %}
                        입금확인중
                    {% elif buy_pro.bidding_state == 3 %}
                        거래완료
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>


<!-- jQuery -->
    <script src="../../static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../static/js/bootstrap.min.js"></script>

</body>
</html>

realtime_bidding/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="../../static/css/my_page.css" rel="stylesheet">
    <link href="../../static/css/realtime_bidding.css" rel="stylesheet">
    <link href="../../static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include "header.html" %}
<div id="naver_id_login"></div>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">회원가입 페이지
            <small>입력하신 이메일은 아이디로 이용됩니다!</small>
        </h1>
    </div>
</div><br><br>
<form action="." method="post" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}

    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-6">
            <input type="email" class="form-control" id="id_email" placeholder="Email" name="email">
        </div>
    </div>

    <div class="form-group naver_id">
        <label for="inputEmail3" class="col-sm-2 control-label">Naver_id</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="id_naver_id" placeholder="naver id" name="naver_id">
        </div>
    </div>

    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">name</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="id_name" placeholder="name" name="name">
        </div>
    </div>

    <div class="form-group naver_form">
        <label for="inputEmail3" class="col-sm-2 control-label">password</label>
        <div class="col-sm-6">
            <input type="password" class="form-control" id="id_password" placeholder="password" name="password">
        </div>
    </div>

    <div class="form-group naver_form">
        <label for="inputEmail3" class="col-sm-2 control-label">password_check</label>
        <div class="col-sm-6">
            <input type="password" class="form-control" id="id_password_check" placeholder="password_check" name="password_check">
        </div>
    </div>

    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Phone_num</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="id_phone_num" placeholder="Phone_number" name="phone_num">
        </div>
    </div>

    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Address</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="id_address" placeholder="address" name="address">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>

</form>
</body>
</html>
{% include "register_script.html" %}

realtime_bidding/templates/register_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="../../static/css/realtime_bidding.css" rel="stylesheet">
    <link href="../../static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include "header.html" %}
<a href="http://127.0.0.1:8000/branch/register">회원가입하기</a><br>
<br> 네이버 아이디를 이용해 가입하시려면 아래 버튼을 클릭해 주세요!
<div id="naver_id_login"></div>


<script src="../../static/js/jquery.js"></script>
<script type="text/javascript" charset="utf-8" src="../../static/js/jquery_cookie/jquery.cookie.js"></script>
<script type="text/javascript" charset="utf-8" src="../../static/naver_login/naverLogin_latest.js"></script>
<script type="text/javascript">
    var naver_id_login = new naver_id_login("sxBMyMNzazWu83yKLKq8", "http://127.0.0.1:8000/branch/register");
    var state = naver_id_login.getUniqState();
    naver_id_login.setButton("white", 3, 50);
    naver_id_login.setState(state);
    naver_id_login.init_naver_id_login();

</script>
</body>
</html>

realtime_bidding/templates/register_script.html
<script src="../../static/js/jquery.js"></script>
<script type="text/javascript" charset="utf-8" src="../../static/js/jquery_cookie/jquery.cookie.js"></script>
<script type="text/javascript" charset="utf-8" src="../../static/naver_login/naverLogin_latest.js"></script>
<script type="text/javascript">
    $('.naver_id').hide();
    var naver_id_login = new naver_id_login("sxBMyMNzazWu83yKLKq8", "http://127.0.0.1:8000/branch/register");
    var state = naver_id_login.getUniqState();
    naver_id_login.setButton("white", 3, 50);
    naver_id_login.setState(state);
    naver_id_login.get_naver_userprofile("a()");

    function a (){
        var id = naver_id_login.getProfileData("id");
        var name = naver_id_login.getProfileData("name");
        var email = naver_id_login.getProfileData("email");
        $('#id_naver_id').val(id);
        $('#id_name').val(name);
        $('#id_email').val(email);
        $('#id_password').val(id);
        $('#id_password_check').val(id);
        //$('.naver_form').hide();
    }
</script>

realtime_bidding/templates/register_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include "header.html" %}
회원가입 성공!
<a href="../../">홈으로</a>

</body>
</html>